# Generated by Django 5.2.6 on 2025-09-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_user_password_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='idChat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='idMessage',
        ),
        migrations.RemoveField(
            model_name='user',
            name='idUser',
        ),
        migrations.AddField(
            model_name='chat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
